### ISSUE TITLE
update links & remove dead links to mybbsecurity.net

### ISSUE THREAD

**Issue by andrewjs18** [mybb/docs.mybb.com#103]
some links need to be updated as well as removing the 5 or so dead links that point to mybbsecurity.net

http://docs.mybb.com/1.8/administration/security/recovery/

**Comment by JoshHarmon** [comment]
I'm upgrading this to high priority because of the malvertising on the domain. We can't have a security-related page linking users to possible drive-by downloads.

**Comment by JoshHarmon** [comment]
Forgot to tag this issue on 9fcd68d262b46c4cc75497365832ede5300c0e3c, which should resolve these things.

**Comment by JoshHarmon** [comment]
Looks like I made a syntax error somewhere...

Edit: Looks like I forgot about the change to rouge, since the code blocks are generating weirdly. I don't know if that's what caused the failure, or if it's something else, but I can't reproduce the failure locally.

**Comment by andrewjs18** [comment]
this has been resolved!
