### ISSUE TITLE
Add a new page for database connection refused

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/docs.mybb.com#118]
https://gyazo.com/0a96164ea30ad8513a7553a98ad036ac

We should add a page on how to fix that error, I see a lot of support topics relating to it.

**Comment by katosdev** [comment]
I'll take this.

**Comment by katosdev** [comment]
Completed: https://github.com/mybb/docs.mybb.com/commit/16f04844be4b38f230c8a0b35be80723417dacba

**Comment by Ben-MyBB** [comment]
Thanks for contributing.
