### ISSUE TITLE
Detailed functions help docs

### ISSUE THREAD

**Issue by katosdev** [mybb/docs.mybb.com#122]
Been speaking with a good friend of mine and we both agreed that having extended documents covering the MyBB functions would be very useful.

Would and dev such as @euantorano or @Devilshakerz etc be able to whip up a short list and we can all add to it as we go on? 

Thanks!

**Comment by dequeues** [comment]
https://crossreference.mybb.de/nav.html?_functions/index.html - all functions.
https://crossreference.mybb.de/inc/functions.php.html - functions.php

If you click the function it'll give you the PHPDoc

**Comment by katosdev** [comment]
@dequeues great, that's perfect! 
Should we maybe consider adding these on /docs/ or such? @euantorano @Ben-Conway ?
Just spit-balling some ideas here ;)

**Comment by euantorano** [comment]
It would be good if they were on an official domain, yeah. @Stefan-ST does a good job keeping the `mybb.de` ones up to date, but it might look better to have an "official" one under the .com domain.

**Comment by Destroy666x** [comment]
I don't think that's needed and optimal, just link the crossreference somewhere, no matter where it's hosted

**Comment by katosdev** [comment]
@euantorano could have a masked domain, and have functions.mybb.com link to the `mybb.de` ones.
