### ISSUE TITLE
Secure URLs where possible

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/docs.mybb.com#123]
Edit - most taken care of in dbd0a0637d18d555c40d18fdc448519be9c1c8b2

Others that should be taken care of:

dev.mybb.com URLs can potentially be found on https://web.archive.org/web/20131029144443/http://dev.mybb.com

There are some other software URLs (you can find them by a simple "http://" search in a text editor, and they may be upgradable.

Most other URLs are example domains and don't necessarily need to be updated.

**Comment by andrewjs18** [comment]
images on this site need to be fixed so they're loading over https: https://docs.mybb.com/1.8/faq/database-errors/

images here also need to be moved to the mybb server and corrected to load over https: https://docs.mybb.com/1.8/faq/using-a-cdn-with-mybb/

**Comment by JoshHarmon** [comment]
Closing now that images have been rehosted, and the dev.mybb.com links now point to the Internet Archive pages.
