### ISSUE TITLE
Port the old Database Restore documentation to 1.8

### ISSUE THREAD

**Issue by euantorano** [mybb/docs.mybb.com#153]
The old 1.6 documentation has a guide on [restoring a MyBB database](https://docs.mybb.com/1.6/Database-Restore/). This should be updated for 1.6 and should be fleshed out a little (with screenshots of the restore process within phpMyAdmin for example).

Also, the restore process should be described for other database management systems such as PostgreSQL.

**Comment by AndreRl** [comment]
I think this will be beneficial now more than ever as IcyBoards is closing down and this is what's basically required. I could probably get this done for PhpMyAdmin, PgAdmin and SSH. Opinion? @euantorano

**Comment by andrewjs18** [comment]
sure, submit a PR and we'll check it out.

**Comment by AndreRl** [comment]
This issue should be marked as closed.
