### ISSUE TITLE
Upgrade guide isn't working

### ISSUE THREAD

**Issue by greencopper** [mybb/docs.mybb.com#161]
I have just followed the guide in order to upgrade from version 1.8.12 to 1.8.14. Since this is a full upgrade I downloaded all the files and copied the files over (overwrite) the old ones. Afterwards MyBB isn't working and I am getting the following very unhelpful message:

```
MyBB Internal: One or more warnings occurred. Please contact your administrator for assistance.
```
And:

```
MyBB has experienced an internal error and cannot continue.

Please contact the MyBB Group for technical support.
```

So following the guide to the letter isn't working, but I don't know what the problem is in order to debug.

**Comment by andrewjs18** [comment]
closing this as it's better to discuss on the 1.8 support forums here: https://community.mybb.com/forum-176.html

**Comment by greencopper** [comment]
I am not going to register on the forum, I haven't got time for that. The error is valid, I have re-tested this 3 times using a backup. As soon as you overwrite all the files, the forum is out of order, so the documentation isn't correct. Please test a full upgrade from version 1.8.12 to 1.8.14. Most likely nobody bothered to test the documentation/upgrade procedure.

**Comment by andrewjs18** [comment]
I upgraded my big board from 1.8.12 to 1.8.14 last week without any issues.  these issues need to be discussed on the forum as that's the proper venue for such problems...

**Comment by JordanMussi** [comment]
Did you run the upgrade script?

https://mybb.com/versions/1.8.13/
> Running the upgrade script is required when upgrading to this release.

You need to run the upgrade script since you are passing 1.8.13 when upgrading from 1.8.12 to 1.8.14.
