### ISSUE TITLE
Backup/Export Data Needs Clarification

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybb/docs.mybb.com#184]
Step #1 needs a bit of clarification in exactly where to go to disable Plugins.

This is the correct "drill-down" to find the Disable All Plugins setting.

AdminCP >> Configuration >> Board Settings >> General Configuration

"disable all plugins by navigating to Configuration"

Should be changed to...

"disable all plugins by navigating to Configuration, Board Settings, General Configuration"

**Comment by euantorano** [comment]
Resolved in #185
