### ISSUE TITLE
Formatting issue: 1.8/faq/database-errors.md

### ISSUE THREAD

**Issue by yuliu** [mybb/docs.mybb.com#187]
Why the following input is parsed as a whole heading?

Ahh I see, maybe should use `&lt;` and `&gtl` instead of `<` and `>` in headers.

```
# Table <table> doesn't exist

Missing a table? First, consider a few key things:

- Is this table a core table that ships with MyBB?
- Is this table from a plugin / extension?
- What were you doing before this error appeared?
```

# Table <table> doesn't exist

Missing a table? First, consider a few key things:

- Is this table a core table that ships with MyBB?
- Is this table from a plugin / extension?
- What were you doing before this error appeared?

[the link is so long](https://github.com/mybb/docs.mybb.com/blob/gh-pages/1.8/faq/database-errors.md#table--doesnt-existmissing-a-table-first-consider-a-few-key-thingsis-this-table-a-core-table-that-ships-with-mybbis-this-table-from-a-plugin--extensionwhat-were-you-doing-before-this-error-appearedif-the-table-is-a-core-tableif-the-missing-table-is-a-core-table-you-should-be-asking-yourself-what-you-were-doing-if-you-were-installing-a-clean-copy-of-mybb-then-try-to-drop-your-database-and-rebuild-it-with-the-provided-installerif-you-were-updating-you-should-follow-the-guidance-in-the-upgrade-guideif-you-were-merging-an-old-database-to-yours-then-you-can-check-the-merge-troubleshooting-document-for-troubleshooting-stepsif-the-table-is-from-a-plugindisable-the-plugin-and-uninstall-it-you-can-then-reinstall-it-later-if-needed-but-ensure-that-the-plugin-is-compatible-with-your-version-of-mybbtip-you-can-sometimes-change-the-compatibility-within-the-plugin-file-like-soreturn-arrayname-example-plugindescription-this-is-an-example-pluginwebsite-authorwebsitecompluginauthor-katosauthorsite-authorsitecomversion-118guid--2418077c65561fe2bd0ac601bdb0c889compatibility--18change-the-compatibility-value-to-your-version-for-example-from-16-to-18-to-try-and-run-a-former-mybb-16x-plugin-on-18x-note-that-this-doesnt-always-work-as-some-plugins-may-depend-on-deprecated-functionality-from-the-mybb-16-seriesuseful-linkshow-to-use-putty-on-windows)

```
# Table &lt;table&gt; doesn't exist

Missing a table? First, consider a few key things:

- Is this table a core table that ships with MyBB?
- Is this table from a plugin / extension?
- What were you doing before this error appeared?
```

# Table &lt;table&gt; doesn't exist

Missing a table? First, consider a few key things:

- Is this table a core table that ships with MyBB?
- Is this table from a plugin / extension?
- What were you doing before this error appeared?

**Comment by euantorano** [comment]
That's definitely an interesting issue/bug in the Markdown processing 😆
