### ISSUE TITLE
TOC fading effect

### ISSUE THREAD

**Issue by pkill37** [mybb/docs.mybb.com#30]
The TOC's fading effect is tacky and unnecessary. We should remove it.

Thoughts?

**Comment by JordanMussi** [comment]
What effect? I scroll past it and like everything else on the page it scrolls up and then becomes hidden.

**Comment by Kaeden** [comment]
I personally have nothing against changing/removing this effect.

**Comment by JordanMussi** [comment]
I also support this (found the effect now :wink:).

**Comment by itsaphel** [comment]
I believe it's still there, I don't have a big issue with it but I find it unnecessary tbh, it'd be better as static.
