### ISSUE TITLE
Anchors

### ISSUE THREAD

**Issue by JordanMussi** [mybb/docs.mybb.com#31]
The TOC/anchors don't behave as they should. For example this link: https://mybb.github.io/1.8/moderation/forums-posts/#toc_2 could end up broken and pointing to the wrong section if the order page content is modifyed or a new anchor is added above.
The 1.6 docs has anchors like `#Adding.2FEditing_an_Announcement`, however, in this new docs site we should use `#adding-editing-an-announcement` not `#toc_2`.

**Comment by pkill37** [comment]
I don't know what changed, but apparently this has been fixed. For example:

http://docs.mybb.com/1.8/install/#downloading-the-mybb-files

Links won't break now if we change things around. Plus they look nicer. :)
