### ISSUE TITLE
Mail FAQ Uptodate?

### ISSUE THREAD

**Issue by trans** [mybb/docs.mybb.com#38]
Is the bottom of this FAQ still correct? I looked for `mail($to...` in functions.php and could not find it.

https://github.com/mybb/docs.mybb.com/blob/gh-pages/1.8/faq/mail.md

**Comment by pkill37** [comment]
`mail()` is a native PHP function.

http://php.net/manual/en/function.mail.php

**Comment by trans** [comment]
I know that. That's not what I was talking about. Did you look at the FAQ I linked to? At the bottom it says:

> Some webhosts have various restrictions on PHP mail. Some hosts require that the
>  From address be a | mailbox address on their server. Other hosts may disable the
>  mail function completely. Please ask your webhost if there are any special restrictions
>  they have on sending mail via PHP.
> 
> If your webhost has restricted that only mails from there own domain is allowed, try to
>  edit the file inc/functions.php. Look for:
> 
> ```
>   mail($to, $subject, $message, $headers);
> ```
> 
> and include above:
> 
> ```
>   ini_set("sendmail_from", " forum@YOURDOMAIN.com "); 
> ```
> 
> Then it should look like this:
> 
> ```
>   ini_set("sendmail_from", " forum@YOURDOMAIN.com "); 
>   mail($to, $subject, $message, $headers);
> ```
> 
> YOURDOMAIN must be replaced by the domain where the forum is hosted.

But I looked at my functions.php file and can not find the line specified. So it appears that this FAQ is not up to date.

**Comment by Destroy666x** [comment]
@trans is right, this line doesn't exist. And it's not the only doc that should be updated for 1.8.
