### ISSUE TITLE
Merge 1.8.1 phpbb3

### ISSUE THREAD

**Issue by kanadaj** [mybb/docs.mybb.com#39]
Converted my phpbb3 forum to mybb, however it left the emoticons in their phpbb3 HTML format. It also kept not migrating some users (not sure about the specific users, but on first try I lost about 250 from 2600, later this got reduced to 45 missing, checked by SELECT COUNT(*)... on the tables

**Comment by Destroy666x** [comment]
How is this connected with the docs site? Please create support threads in our forums: http://community.mybb.com/forum-180.html
