### ISSUE TITLE
MyBB 1.6 Documentation links bug

### ISSUE THREAD

**Issue by Ikerepc** [mybb/docs.mybb.com#45]
So when you access to http://docs.mybb.com/1.6/ and click to common problems or faq, you got a list of sublinks for help. But clicking them, they lead you to error page.

Like here:
Common problems: http://docs.mybb.com/1.6/Common-Problems/
Click on any link lead to error page

**Comment by JoshHarmon** [comment]
Doesn't behave like that for me. On Common Problems, clicking most of the links goes nowhere as whatever generated the links from the old wiki seems to me be in the old MediaWiki format.

**Comment by Ikerepc** [comment]
Ok. It redirect nowhere, but I think it should redirect somewhere. Can it be fixed?

**Comment by JoshHarmon** [comment]
I'll work on it. Thanks for mentioning it.

**Comment by Ikerepc** [comment]
I see that all that questians are answered at: http://docs.mybb.com/1.6/
So can you (or I can try) add new links to that or delete that pages?

**Comment by JoshHarmon** [comment]
I'll go through the 1.6 pages and make sure the articles have proper links. You don't have to worry about it - I need something to occupy myself with for the next 45 minutes :).

**Comment by JoshHarmon** [comment]
@Ikerepc I have fixed as many broken links as I can find for the moment. Please do not hesitate to open another issue if you find more, but most should be fixed at this time.

Edit: Relevant commits below:
f72339a
6ebf87c
ab90a59
3099b60

^JH
