### ISSUE TITLE
1.6 Database table links don't work

### ISSUE THREAD

**Issue by Ikerepc** [mybb/docs.mybb.com#46]
Here http://docs.mybb.com/1.6/Database-Tables/
Links don't work.

When I access to it, I got message "Unfortunately, the page you tried to access could not be found. If you were brought to this page from our website, please contact us with a description of how you came to this page. You can also search for what you were looking for below."

**Comment by JordanMussi** [comment]
The links are structured incorrectly.

`{{ site.baseurl }}/1.6/Database_Tables-mybb_adminlog.html`
Should be:
`{{ site.baseurl }}/1.6/Database-Tables-mybb-adminlog/`

Fixed in Pull Request #47.
