### ISSUE TITLE
Tasks/cron job

### ISSUE THREAD

**Issue by ATofighi** [mybb/docs.mybb.com#61]
https://github.com/mybb/mybb/issues/2087

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/issues/1729

If you grep `docs.mybb.com` in the whole MyBB package, you can find many more links:
- [x] http://docs.mybb.com/Help-Task_System.html
- [x] http://docs.mybb.com/HowTo_Chmod.html (linked at least 2 times)
- [x] http://docs.mybb.com/CHMOD_Files.html (linked at least a few times, should merge it with the above doc)
- [x] http://docs.mybb.com/SEF_URLs.html
- [x] http://docs.mybb.com/Utf8_setup.html
- [x] http://docs.mybb.com/Anonymous_Statistics.html (linked at least 2 times)
- [x] http://docs.mybb.com/Help-Upload_Directory.html
- [x] http://docs.mybb.com/Cookie_Settings.html
- [x] http://docs.mybb.com/165.html

I think that's all, at least I can't find anything else.

**Comment by JN-Jones** [comment]
There are also some in the merge system - at least the chmod page is linked too.

**Comment by Ben-MyBB** [comment]
@JoshHarmon Any idea what was on http://docs.mybb.com/165.html ?

**Comment by Starpaul20** [comment]
It was 1.6.5's release info: https://web.archive.org/web/20140301032709/http://docs.mybb.com/165.html

**Comment by andrewjs18** [comment]
when doing a grep on the mybb install on my test forum, these are the files it's finding that need to be updated with the correct docs.mybb.com links:

~~`admin/modules/tools/system_health.php:925:  $page->output_error("<p><em>{$errors} {$lang->error_chmod}</span></strong> {$lang->chmod_info} <a href=\"http://docs.mybb.com/HowTo_Chmod.html\" target=\"_blank\">MyBB Docs</a>.</em></ p>");`~~

~~`inc/languages/english/admin/tools_tasks.lang.php:74:$l['confirm_task_enable'] =        "<strong>WARNING:</strong> You are about to enable a task that is only meant to be run via cron (Please see the <a href=\"http://docs.mybb.com/Help Task_System.html\" target=\"_blank\">MyBB Docs</a> for more information). Continue?";`~~

~~`inc/languages/english/admin/config_settings.lang.php:86:$l['error_chmod_settings_file'] = "The settings file \"./inc/settings.php\" isn't writable. Please CHMOD to 777.<br />For more information on CHMODing, see the <a href=\"http://docs.mybb.com/HowTo_Chmod.html\" target=\"_blank\">MyBB Docs</a>.";`~~

~~`inc/languages/english/admin/tools_system_health.lang.php:77:$l['error_db_encoding_not_set'] = "Your current setup of MyBB is not setup to use this tool yet. Please see the <a href=\"http://docs.mybb.com/Utf8_setup.html\">MyBB Docs</a> for more information on how to set it up.";`~~

**Comment by andrewjs18** [comment]
@Destroy666x, are you finding anything else that I didn't note above?

**Comment by andrewjs18** [comment]
documenting more files that need to be updated...all of these are within the /install directory...some redirect properly and some don't...we should probably update all of them regardless for the sake of uniformity.  

~~`resources/settings.xml:267: <description><![CDATA[Search engine friendly URLs change the MyBB links to shorter URLs which search engines prefer and are easier to type. showthread.php?tid=1 becomes thread-1.html. <strong>Once this setting is enabled you need to make sure you have the MyBB .htaccess in your MyBB root directory (or the equivalent for your web server). Automatic detection may not work on all servers.</strong> Please see the <a href="http://docs.mybb.com/SEF_URLs.html">MyBB Docs</a> for assistance.]]></description>`~~

~~`resources/settings.xml:675: <description><![CDATA[When set to yes, this setting will attempt to mark the parent forums of a sub-forum as read if there are no more unread posts. Please note that this setting can lead to a decrease in performance and multiple database queries and therefore must be treated as experimental. See the <a href="http://docs.mybb.com/165.html">MyBB Docs</a> for more information regarding this change.]]></description>`~~

~~`resources/language.lang.php:61: <p>While there is nothing wrong with this, it is recommended that your upload the contents of the \"Upload\" directory and not the directory itself.<br /><br />For more information please see the <a href=\"http://docs.mybb.com/Help-Upload_Directory.html\" target=\"_blank\">MyBB Docs</a>.</p>`~~

~~`resources/language.lang.php:77:<p><input type="checkbox" name="allow_anonymous_info" value="1" id="allow_anonymous" checked="checked" /> <label for="allow_anonymous"> Send anonymous statistics about your server specifications to the MyBB Group</label> (<a href="http://docs.mybb.com/Anonymous_Statistics.html" style="color: #555;" target="_blank"><small>What information is sent?</small></a>)</p>';`~~

~~`resources/language.lang.php:145:$l['req_step_error_configfile'] = 'The configuration file (inc/config.php) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`resources/language.lang.php:146:$l['req_step_error_settingsfile'] = 'The settings file (inc/settings.php) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`resources/language.lang.php:148:$l['req_step_error_uploaddir'] = 'The uploads directory (uploads/) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`resources/language.lang.php:149:$l['req_step_error_avatardir'] = 'The avatars directory (uploads/avatars/) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`resources/language.lang.php:150:$l['req_step_error_cssddir'] = 'The css directory (css/) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`resources/language.lang.php:241: <th colspan="2" class="first last">Cookie settings <a title="What\'s this?" target="_blank" href="http://docs.mybb.com/Cookie_Settings.html">(?)</a></th>`~~

~~`resources/language.lang.php:358:$l['upgrade_send_stats'] = "<p><input type=\"checkbox\" name=\"allow_anonymous_info\" value=\"1\" id=\"allow_anonymous\" checked=\"checked\" /> <label for=\"allow_anonymous\"> Send anonymous statistics about your server specifications to the MyBB Group</label> (<a href=\"http://docs.mybb.com/Anonymous_Statistics.html\" style=\"color: #555;\" target=\"_blank\"><small>What information is sent?</small></a>)</p>";`~~

**Comment by andrewjs18** [comment]
@Ben-Conway

**Comment by Destroy666x** [comment]
Well, I listed all instances I found above. There were no changes so they still are broken

**Comment by andrewjs18** [comment]
yeah, I just wanted to list out where all of those instances were in the files to make it easier for us to fix.

**Comment by andrewjs18** [comment]
most of this stuff is fixed in these PRs:
https://github.com/mybb/mybb/pull/2452
https://github.com/mybb/mybb/pull/2453

**Comment by andrewjs18** [comment]
merge links that need to be updated from what I've found doing a grep on the merge package:

~~`index.php:620: $errors['attachments_check'] = $lang->requirementspage_chmoduploads.' <a href="http://docs.mybb.com/1.8/install/#file-permissions" target="_blank">'.$lang->requirementspage_chmod.'</a>'.$lang->requirementspage_chmoduploads;`~~

~~`language/global.lang.php:196:$l['upload_not_writeable'] = 'The uploads directory ({1}) is not writable. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be written to.';`~~

~~`language/global.lang.php:197:$l['download_not_readable'] = 'The directory could not be read. Please adjust the <a href="http://docs.mybb.com/CHMOD_Files.html" target="_blank">chmod</a> permissions to allow it to be read from and ensure the URL is correct. If you are still experiencing issues, please try the full system path instead of a URL (ex: /var/www/htdocs/path/to/your/old/forum/uploads/ or C:/path/to/your/old/forum/upload/). Also ensure access isn\'t being blocked by a htaccess file.';`~~

**Comment by andrewjs18** [comment]
fixed broken merge URLs with this PR: https://github.com/mybb/merge-system/pull/199

@JN-Jones

**Comment by andrewjs18** [comment]
final 2 issues are fixed in this PR: https://github.com/mybb/mybb/pull/2454

closing!!
