### ISSUE TITLE
Update plugin hooks page for 1.8.6

### ISSUE THREAD

**Issue by psde** [mybb/docs.mybb.com#62]
I added two new hooks for the calendar while fixing a bug. As per https://github.com/mybb/mybb/pull/2006#issuecomment-117580948 the plugin hooks page should be regenerated.

**Comment by JN-Jones** [comment]
@euantorano IIRC you added that page ;)

**Comment by euantorano** [comment]
I can run this tonight if nobody beats me to it.

**Comment by JN-Jones** [comment]
I'd wait till we prepare the release packages as the line numbers may get changed till then.

**Comment by euantorano** [comment]
I think Paul might of added it initially using my tool ;)

**Comment by euantorano** [comment]
True, there's a higher chance of me forgetting then. I've been meaning to automate it.
