### ISSUE TITLE
1.8 docs have misleading 1.6 info

### ISSUE THREAD

**Issue by Destroy666x** [mybb/docs.mybb.com#65]
As I mentioned long time ago here: http://community.mybb.com/thread-157558.html, at least several 1.8 docs have still misleading 1.6 info. For example http://docs.mybb.com/1.8/administration/security/protection/#fine-tuning-the-admin-cp mentions a tutorial for adding PIN to ACP..

**Comment by JoshHarmon** [comment]
Yep, I've made a note of these and was about to start migrating all my TODO list to Issues!

**Comment by JoshHarmon** [comment]
AFAIK, all of these issues have been fixed. If not, this issue should be reopened with specific inaccuracies.

**Comment by Destroy666x** [comment]
Could have mentioned that the PIN can be changed in `inc/config.php` now.
