### ISSUE TITLE
Move "Creating a new page" under its own subcategory

### ISSUE THREAD

**Issue by Destroy666x** [mybb/docs.mybb.com#66]
It doesn't have much to do with templates IMO, I wouldn't look for it there: http://docs.mybb.com/1.8/development/plugins/templates/#creating-a-new-page-action

**Comment by JoshHarmon** [comment]
Also on my TODO list :P.

And if you think I'm kidding, Ben C can vouch for it!

**Comment by JoshHarmon** [comment]
Done in 040b5405f4fc07d77439c4a71b15cc61a7e13d9f
