### ISSUE TITLE
Expand 1.8/administration/security/2fa.md with setup guide, possible pitfalls

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/docs.mybb.com#69]
- Setup help/instructions, other than just a table with obnoxiously-large links to apps.
- Explain the 30-second precision and how timezone differences between server and client matter

I don't know what else, but a screenshot here or there in setup would also be nice, instead of endless text.

**Comment by JN-Jones** [comment]
> Explain the 30-second precision and how timezone differences between server and client matter

Wasn't there some discussion about fixing/changing this in the core? Not sure atm.

Also we should link a few more apps, especially for windows phone.

**Comment by Destroy666x** [comment]
There was, a delay setting should be added in 1.8.6 IMO
