### ISSUE TITLE
Setting up a CDN with 1.8

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/docs.mybb.com#70]
Guide for how to configure CDN use within 1.8. It can be a really helpful feature for reducing request load on a server, so it's something that should be documented.

**Comment by katosdev** [comment]
I will start work on this :+1:

**Comment by euantorano** [comment]
This thread may be of use: http://community.mybb.com/thread-160349.html

**Comment by Ben-MyBB** [comment]
Thanks @katosdev

**Comment by katosdev** [comment]
@euantorano - cheers, will use this as a base guide.
@Ben-Conway no worries

**Comment by katosdev** [comment]
Sent a pull request here: https://github.com/mybb/docs.mybb.com/pull/104

**Comment by andrewjs18** [comment]
closed.  thanks for contributing, @katosdev.

**Comment by katosdev** [comment]
No worries @andrewjs18
