### ISSUE TITLE
Antispam documentation

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/docs.mybb.com#71]
1.8 brought some nice features into the core. The Documentation does an awful job of [highlighting](http://docs.mybb.com/1.8/administration/spam/) them.

Here are some ideas:
- [x] Purge Spammer
- [x] StopForumSpam integration
- [x] Captcha options
- [x] AYAH
- [x] reCaptcha
- [x] "noCaptcha" reCaptcha
- [x] Question/Answer
  - [x] How to choose effective questions
- [x] GD image (or maybe this shouldn't be documented anymore...)
- [ ] Allow website field for certain groups only
- [ ] Screenshots for various things

**Comment by Destroy666x** [comment]
There's also StopForumSpam

**Comment by JoshHarmon** [comment]
I thought it had to be disabled for some reason, but I might have confused that with something else.

Added it anyways, because I'm probably out of the loop a bit.

**Comment by Destroy666x** [comment]
That was in 1.8.0 over a half year ago. It's fixed in 1.8.1.

**Comment by JoshHarmon** [comment]
Well... I guess this (forgetfulness) is what happens when you don't actively have a board for a year and a half.

**Comment by euantorano** [comment]
Nice one Josh!
