### ISSUE TITLE
Hide the Security Hall of Fame placeholder

### ISSUE THREAD

**Issue by dvz** [mybb/docs.mybb.com#85]
Currently http://www.mybb.com/get-involved/security/hall-of-fame/ is not being used (will be in MyBB 2.x) - links from http://www.mybb.com/get-involved/security/ should be removed or the _HoF_ page itself should contain an appropriate notice.

**Comment by JoshHarmon** [comment]
Wrong repo, @Devilshakerz. You're looking for mybb/mybb.com :P.

**Comment by Destroy666x** [comment]
mybb.com*

**Comment by JoshHarmon** [comment]
Tired me was tired, @Destroy666x. You win.
