### ISSUE TITLE
Incorrect images + hotlinking

### ISSUE THREAD

**Issue by Destroy666x** [mybb/docs.mybb.com#90]
Google buttons are incorrect: http://docs.mybb.com/1.8/administration/security/2fa/ Also, none of the buttons (and possibly other images in docs) should be hotlinked.

**Comment by Destroy666x** [comment]
What about other hotlinked images e.g. the Apple one?

**Comment by JoshHarmon** [comment]
I'm not aware of any more hotlinked images, but I'll keep looking around.
