### ISSUE TITLE
upgrade page improvements

### ISSUE THREAD

**Issue by andrewjs18** [mybb/docs.mybb.com#95]
1- add a small tutorial on how to restrict all access to the forum via .htaccess
2- provide the path in the admin cp to deactivate/disable all plugins prior to the upgrade

http://docs.mybb.com/1.8/install/upgrade/

**Comment by katosdev** [comment]
@andrewjs18 "Restrict all access to the forum via .htaccess" - would you not be best recommending closing the site via the board offline setting? Just a quick suggestion.
Also, give me a shout should you need a hand with this.

**Comment by Destroy666x** [comment]
`.htaccess` restriction is better in case something goes wrong

**Comment by andrewjs18** [comment]
The .htaccess already exists in the docs, it's just not on the upgrade page.  once we get these page build failure errors fixed, I'll copy it over: http://docs.mybb.com/1.8/administration/security/recovery/#restrict-access-to-the-forum

The 2nd part is also easy to add, once the aforementioned issue is resolved.

**Comment by Ben-MyBB** [comment]
I'm going to start work on this now.

**Comment by Ben-MyBB** [comment]
This is completed, just need to merge @andrewjs18 's PR once the build errors are fixed.

**Comment by andrewjs18** [comment]
this should be fixed by this PR:
#112

**Comment by andrewjs18** [comment]
everything has been added!
