### ISSUE TITLE
cookie generator website

### ISSUE THREAD

**Issue by andrewjs18** [mybb/docs.mybb.com#99]
It might be a good idea to have an official mybb cookie generator website so its availability can be maintained alongside the mybb project.

**Comment by Destroy666x** [comment]
Why a website? If you mean the cookie domain/path generator hosted by DenisTT, we could simply add Javascript that does the same directly in the doc.

**Comment by JoshHarmon** [comment]
WIP: https://jsfiddle.net/hf5n0c8g/2/

**Comment by andrewjs18** [comment]
javascript directly inside the doc works fine for me, too.

**Comment by andrewjs18** [comment]
how's this coming along, @JoshHarmon

**Comment by JoshHarmon** [comment]
79fdf98680083c7f7fe6d7c70de93e0eb70a54fc resolves this.
